stages:
  data_cleaning:

    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw
    - src/data/data_cleaning.py
    params:
    - data_cleaning.test_size
    outs:
    - data/cleaned

  feature_engineering:

    cmd: python src/features/feature_engineering.py
    deps:
    - data/cleaned
    - src/features/feature_engineering.py
    outs:
    - data/processed
    


